<?xml version="1.0" encoding="utf-8"?><Database Name="TradeWorkstation" Class="TradeWorkstationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.123.41;Initial Catalog=TradeWorkstation;Persist Security Info=True;User ID=TradeWorkstation" SettingsObjectName="DataSource.Properties.Settings" SettingsPropertyName="TradeWorkstationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BlackList" Member="BlackList">
    <Type Name="BlackList">
      <Column Name="BID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SendTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Item_BlackList" Member="Item" ThisKey="IID" OtherKey="IID" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Category">
    <Type Name="Category">
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Category" Member="Category2" ThisKey="CID" OtherKey="PID" Type="Category" />
      <Association Name="Category_Item" Member="Item" ThisKey="CID" OtherKey="CID" Type="Item" />
      <Association Name="Category_Category" Member="Category1" ThisKey="PID" OtherKey="CID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pic" Member="Pic">
    <Type Name="Pic">
      <Column Name="PID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_Pic" Member="Item" ThisKey="IID" OtherKey="IID" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Item">
    <Type Name="Item">
      <Column Name="IID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,4)" CanBeNull="true" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Bargain" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Way" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[From]" Member="From" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[To]" Member="To" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RunTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PostTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_BlackList" Member="BlackList" ThisKey="IID" OtherKey="IID" Type="BlackList" />
      <Association Name="Item_Pic" Member="Pic" ThisKey="IID" OtherKey="IID" Type="Pic" />
      <Association Name="Item_Store" Member="Store" ThisKey="IID" OtherKey="IID" Type="Store" />
      <Association Name="Category_Item" Member="Category" ThisKey="CID" OtherKey="CID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Store" Member="Store">
    <Type Name="Store">
      <Column Name="SID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StoreTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_Store" Member="Item" ThisKey="IID" OtherKey="IID" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SysLog" Member="SysLog">
    <Type Name="SysLog">
      <Column Name="LID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LogContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LogTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>